#!/bin/sh
SERVICE_NAME=AcmWebService
PATH_TO_JAR=/var/lib/jenkins/workspace/acm-webservice/backend/target/AcmWebService.war
LOG_PATH_NAME=/var/log/AcmWebService.log
PID_PATH_NAME=/tmp/AcmWebService.pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            if [ ! -f $PATH_TO_JAR ]; then
                echo "$SERVICE_NAME can't be started! $PATH_TO_JAR does not exits!!"
            else
                nohup java -jar $PATH_TO_JAR >> $LOG_PATH_NAME 2>&1&
                echo $! > $PID_PATH_NAME
                echo "$SERVICE_NAME started ..."
            fi
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
